/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
  sector?: LocaleString;
  problem?: LocaleText;
  solution?: LocaleText;
  metric?: string;
  metricLabel?: LocaleString;
  body?: LocaleText;
  testimonial?: {
    quote?: LocaleText;
    author?: string;
  };
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  };
  date?: string;
};

export type LocaleString = {
  _type: "localeString";
  it?: string;
  en?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type LocaleText = {
  _type: "localeText";
  it?: string;
  en?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ContactSubmission = {
  _id: string;
  _type: "contactSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  company?: string;
  email?: string;
  message?: string;
  submittedAt?: string;
  locale?: string;
  handled?: boolean;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: Slug;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  description?: LocaleText;
  siteUrl?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  keywords?: Array<string>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CaseStudy
  | LocaleString
  | SanityImageCrop
  | SanityImageHotspot
  | LocaleText
  | Slug
  | ContactSubmission
  | Page
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    title,    description,    siteUrl,    "ogImage": ogImage.asset->url,    keywords  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: LocaleString | null;
  description: LocaleText | null;
  siteUrl: string | null;
  ogImage: string | null;
  keywords: Array<string> | null;
} | null;

// Source: sanity/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)]    | order(coalesce(date, _createdAt) desc){    _id,    title,    "slug": slug.current,    sector,    problem,    solution,    metric,    metricLabel  }
export type CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  title: LocaleString | null;
  slug: string | null;
  sector: LocaleString | null;
  problem: LocaleText | null;
  solution: LocaleText | null;
  metric: string | null;
  metricLabel: LocaleString | null;
}>;

// Source: sanity/queries.ts
// Variable: CASE_STUDY_BY_SLUG_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    sector,    problem,    solution,    metric,    metricLabel,    body,    testimonial,    cover,    "coverAlt": cover.alt,    date  }
export type CASE_STUDY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: LocaleString | null;
  slug: string | null;
  sector: LocaleString | null;
  problem: LocaleText | null;
  solution: LocaleText | null;
  metric: string | null;
  metricLabel: LocaleString | null;
  body: LocaleText | null;
  testimonial: {
    quote?: LocaleText;
    author?: string;
  } | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    _type: "image";
  } | null;
  coverAlt: LocaleString | null;
  date: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "caseStudy" && defined(slug.current)].slug.current
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<string | null>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n    title,\n    description,\n    siteUrl,\n    "ogImage": ogImage.asset->url,\n    keywords\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current)]\n    | order(coalesce(date, _createdAt) desc){\n    _id,\n    title,\n    "slug": slug.current,\n    sector,\n    problem,\n    solution,\n    metric,\n    metricLabel\n  }': CASE_STUDIES_QUERY_RESULT;
    '*[_type == "caseStudy" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    sector,\n    problem,\n    solution,\n    metric,\n    metricLabel,\n    body,\n    testimonial,\n    cover,\n    "coverAlt": cover.alt,\n    date\n  }': CASE_STUDY_BY_SLUG_QUERY_RESULT;
    '*[_type == "caseStudy" && defined(slug.current)].slug.current': CASE_STUDY_SLUGS_QUERY_RESULT;
  }
}
